# Generated by Django 4.2.7 on 2023-12-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert_box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='alert_box/image')),
                ('slide', models.ImageField(blank=True, upload_to='alert_box/slide')),
                ('blog_title', models.CharField(blank=True, max_length=255)),
                ('blog_photo', models.ImageField(blank=True, upload_to='alert_box/blogs_images')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('icons', models.ImageField(blank=True, upload_to='alert_box/icons/')),
            ],
            options={
                'verbose_name': 'Alert_box',
                'verbose_name_plural': 'Alert_boxs',
            },
        ),
        migrations.CreateModel(
            name='Typography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='typography/image')),
                ('slide', models.ImageField(blank=True, upload_to='typography/slide')),
                ('blog_title', models.CharField(blank=True, max_length=255)),
                ('blog_photo', models.ImageField(blank=True, upload_to='typography/blogs_images')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Typography',
                'verbose_name_plural': 'Typographys',
            },
        ),
    ]
