# Generated by Django 4.2.7 on 2023-11-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home_6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='home_6/images')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('picture', models.ImageField(blank=True, upload_to='home_6/pictures')),
                ('picture_about', models.TextField(blank=True)),
                ('icons', models.ImageField(blank=True, upload_to='home_6/icons')),
            ],
            options={
                'verbose_name': 'Home_6',
                'verbose_name_plural': 'Homes_6',
            },
        ),
    ]
