# Generated by Django 4.2.7 on 2023-12-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('columns_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='columns_2',
            options={'verbose_name': 'Portfolio-2-columns', 'verbose_name_plural': 'Portfolio-2-columns'},
        ),
    ]
